### ISSUE TITLE
Some Videos don't have captions, resulting in crashs

### ISSUE THREAD

**Issue by GityUpNow** [jhelgert/IliasDownloaderUniMA#24]
**Describe the bug**
The **scanFolder** method assumes that every Video has a corresponding _ilc_media_caption_MediaCaption_ div to take the video filename from.
Ilias courses are once again inconsistent, with videos that are missing captions, which leads to a crash.

An example would be the VL Einführung in die Politikwissenschaft (HWS 2020) with the ref_id 1017589.

I tried to write a fix [here](https://github.com/jhelgert/IliasDownloaderUniMA/pull/21/commits/1d0adae6a72650e59d0e5538bd54194235589d5d)

```python
Scanning VL Einführung in die Politikwissenschaft (HWS 2020) with 5 Threads....
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)//
https://ilias.uni-mannheim.de/ilias.php?ref_id=997744&cmd=frameset&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/
https://ilias.uni-mannheim.de/ilias.php?ref_id=997745&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/Sitzung 2 (6.10.2020, Schoen)/
https://ilias.uni-mannheim.de/ilias.php?ref_id=1017587&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/Sitzung 3  (13.10. 2020, Traunmüller)/
https://ilias.uni-mannheim.de/ilias.php?ref_id=1017588&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/Sitzung 1 (29.9.2020, Schoen)/
https://ilias.uni-mannheim.de/ilias.php?ref_id=998824&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/Sitzung 4 (20.10.2020, Blom)/
https://ilias.uni-mannheim.de/ilias.php?ref_id=1017589&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Scanning Folder...
VL Einführung in die Politikwissenschaft (HWS 2020)/Dateien/Sitzung 5 (Schmitt-Beck, Aufzeichnung)/
https://ilias.uni-mannheim.de/ilias.php?ref_id=1017590&cmd=view&cmdClass=ilrepositorygui&cmdNode=vi&baseClass=ilrepositorygui
-------------------------------------------------
Traceback (most recent call last):
  File "download.py", line 8, in <module>
    m.downloadAllFiles()
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 341, in downloadAllFiles
    self.scanCourses()
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 303, in scanCourses
    self.searchForFiles(course['name'])
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 290, in searchForFiles
    for r in results:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 289, in <lambda>
    results = ThreadPool(self.params['num_scan_threads']).imap_unordered(lambda x: self.scanHelper(course_name, x), self.to_scan)
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 274, in scanHelper
    self.scanFolder(course_name, el['url'])
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 202, in scanFolder
    el_name = v.find('div', {'class': 'ilc_media_caption_MediaCaption'}).get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Expected behavior**
**scanFolder** should be able to download videos, even if they are missing a corresponding caption div.

**Comment by jhelgert** [comment]
Fixed.
