### ISSUE TITLE
broken since ilias update

### ISSUE THREAD

**Issue by aleyeeey** [jhelgert/IliasDownloaderUniMA#29]
Any plans to update this for the new version of ilias? Since then I cannot run the script anymore.

```python
Traceback (most recent call last):
  File "iliasscript.py", line 5, in <module>
    m.login('ilias_name', 'ilias_password')
  File "/home/aleyc0re/.local/lib/python3.8/site-packages/IliasDownloaderUniMA/IliasDL.py", line 121, in login
    raise ConnectionError("Couldn't log into ILIAS. Make sure your provided uni-id and the password are correct.")
requests.exceptions.ConnectionError: Couldn't log into ILIAS. Make sure your provided uni-id and the password are correct
```

**Comment by jhelgert** [comment]
Unfortunately, I no longer have access to Ilias since I finished my studies, so I can't really work on an update. 

However, as far as I can tell, only the Ilias dashboard has changed, not the login page itself, so the login should still work. If we are lucky, we will only have to adjust this check whether the login was successful:

https://github.com/jhelgert/IliasDownloaderUniMA/blob/5c4d23940df7b9906e2d2e22612bc83cebec7d6f/IliasDownloaderUniMA/IliasDL.py#L120

Otherwise, we should check how the HTML structure has changed. Here I would assume that only a few CSS classes have been renamed.

Anyway, a PR is more than welcome!

**Comment by sephdoto** [comment]
If you want I can help you fix this by giving you access to test :) This would be a REALLY helpful tool to automate and keep files up to date in order to study better! 

I just started uni so I do not have enough coding expertise to fix this on my own :(

**Comment by jhelgert** [comment]
@sephdoto Sorry for the delayed reply. Feel free to drop me an email at `myfirstname.mylastname@posteo.de` regarding the Ilias access. Then I could have a look at it this weekend.
